spring.application.name=resume-ai-backend
spring.ai.ollama.chat.model=llama3.2:latest
#spring.ai.openai.api-key=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database configuration
spring.datasource.url=jdbc:h2:file:./data/resumedb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
resume.app.jwtSecret=======================ResumeGeneratorSecretKeyByAntigravity======================
resume.app.jwtExpirationMs=86400000